In [4]:
import pandas as pd

df1_dict = {
        'id': ['1', '2', '3', '4', '5'],
        'Feature1': ['A', 'C', 'E', 'G', 'I'],
        'Feature2': ['B', 'D', 'F', 'H', 'J']}

df1 = pd.DataFrame(df1_dict, columns = ['id', 'Feature1', 'Feature2'])

df2_dict = {
        'id': ['1', '2', '6', '7', '8'],
        'Feature1': ['K', 'M', 'O', 'Q', 'S'],
        'Feature2': ['L', 'N', 'P', 'R', 'T']}

df2 = pd.DataFrame(df2_dict, columns = ['id', 'Feature1', 'Feature2'])
pd.merge(df1,  df2, on='id')

  id Feature1_x Feature2_x Feature1_y Feature2_y
0  1          A          B          K          L
1  2          C          D          M          N

In [5]:
pd.merge(df1,  df2, on='id', how='outer')

  id Feature1_x Feature2_x Feature1_y Feature2_y
0  1          A          B          K          L
1  2          C          D          M          N
2  3          E          F        NaN        NaN
3  4          G          H        NaN        NaN
4  5          I          J        NaN        NaN
5  6        NaN        NaN          O          P
6  7        NaN        NaN          Q          R
7  8        NaN        NaN          S          T