In [152]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

diabetes = load_diabetes(as_frame=True)
X, y = diabetes.data, diabetes.target

print(y.head())
X.head()

0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
Name: target, dtype: float64

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [153]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=43
)

print(y_train.values[:10])
print(y_test.values[:10])

X_train.head()

[202.  55. 202.  42. 214. 173. 118.  90. 129. 151.]
[ 71.  72. 235. 277. 109.  61. 109.  78.  66. 192.]

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
270,0.005383,0.050680,0.030440,0.083844,-0.037344,-0.047347,0.015505,-0.039493,0.008641,0.015491
41,-0.099961,-0.044642,-0.067641,-0.108956,-0.074494,-0.072712,0.015505,-0.039493,-0.049872,-0.009362
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084492,-0.017646
419,-0.020045,-0.044642,-0.054707,-0.053870,-0.066239,-0.057367,0.011824,-0.039493,-0.074093,-0.005220
338,-0.063635,-0.044642,-0.033151,-0.033213,0.001183,0.024051,-0.024993,-0.002592,-0.022517,-0.059067

In [154]:
model = LinearRegression()
model.fit(X_train, y_train)

coefs = list(zip(X.columns, model.coef_))
coefs = [(name, float(value)) for name, value in coefs]
coefs.append(('intercept', float(model.intercept_)))
coefs

[('age', -60.3998480933362),
 ('sex', -226.08359044269213),
 ('bmi', 529.3849571887339),
 ('bp', 259.9619941214204),
 ('s1', -859.093009334801),
 ('s2', 504.6869733896178),
 ('s3', 157.41085788032728),
 ('s4', 226.29313435521135),
 ('s5', 840.784040604922),
 ('s6', 34.71226555571711),
 ('intercept', 152.0532454782767)]

In [155]:
predictions_on_test = model.predict(X_test)
predictions_on_test[:10]

array([111.74267934,  98.41608992, 168.36714629, 255.06351455,
       168.44138847, 117.60698984, 198.8733865 , 126.2932775 ,
       117.72876579, 224.82776308])

In [156]:
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)
mse_train = mean_squared_error(y_train, y_pred_train)
mse_test = mean_squared_error(y_test, y_pred_test)

rmse_train = np.sqrt(mse_train)
rmse_test = np.sqrt(mse_test)

print("Train RMSE:", rmse_train)
print("Test RMSE:", rmse_test)
print("y min:", y.min())
print("y max:", y.max())
print("y mean:", y.mean())

mse_train, mse_test

Train RMSE: 53.74313536050094
Test RMSE: 53.462991926750504
y min: 25.0
y max: 346.0
y mean: 152.13348416289594

(2888.324598377127, 2858.2915057597897)