In [52]:
import pandas as pd
import numpy as np

business_dates = pd.bdate_range('2021-01-01', '2021-12-31')

tickers = ['AAPL', 'FB', 'GE', 'AMZN', 'DAI']

index = pd.MultiIndex.from_product([business_dates, tickers], names=['Date', 'Ticker'])

market_data = pd.DataFrame(index=index,
                        data=np.random.randn(len(index), 1),
                        columns=['Price'])

market_data.head()

                      Price
Date       Ticker
2021-01-01 AAPL    0.483429
           FB     -0.171072
           GE     -0.319725
           AMZN    1.652028
           DAI    -1.102526

In [53]:
soufian = market_data.pivot_table(values="Price", index="Date", columns="Ticker").pct_change()
print(soufian.shape)
soufian.head()

(261, 5)

Ticker          AAPL      AMZN       DAI        FB         GE
Date
2021-01-01       NaN       NaN       NaN       NaN        NaN
2021-01-04 -3.063755 -0.804835 -2.279225  3.557357   0.379110
2021-01-05 -1.957222 -2.253947 -2.063525 -1.960308  -5.381004
2021-01-06 -0.985893 -1.622685 -1.112569  0.230575  -1.005631
2021-01-07  5.951155  3.797909 -3.114969 -1.510780 -48.586421